[changelog]
header = "# Changelog\n\n"
body = """
{% for group, commits in commits | group_by(attribute="group") %}
## {{ group | upper_first }}
{% for commit in commits %}
- {{ commit.message | upper_first }} ({{ commit.id | truncate(length=7, end='') }})
{% endfor %}
{% endfor %}
"""
footer = "\n"

[git]
filter_unconventional = true
protect_breaking_commits = false
tag_pattern = ".*"


