import type { Metadata } from 'next'
import { Inter } from 'next/font/google'
import './globals.css'
import Image from 'next/image'
import ClientOnly from '@/components/layout/ClientOnly'

const inter = Inter({ subsets: ['latin'] })

export const metadata: Metadata = {
  title: 'Create Next App',
  description: 'Generated by create next app',
}

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode
}>) {
  return (
    <html lang="en">
      <body className={`${inter.className} loading`}>
        <div id="initial-preloader">
          <Image
            src="/logo_wbg.svg"
            alt="App Logo"
            width={120}
            height={120}
            priority
          />
        </div>
        <ClientOnly>{children}</ClientOnly>
      </body>
    </html>
  )
}
