import type { Metadata } from 'next'
import { Inter } from 'next/font/google'
import './globals.css'
import Header from '@/components/appbar/Header'
import BottomNav from '@/components/appbar/BottomNav'
import ClientLayout from '@/components/layout/ClientLayout'
import Image from 'next/image'

const inter = Inter({ subsets: ['latin'] })

export const metadata: Metadata = {
  title: 'Create Next App',
  description: 'Generated by create next app',
}

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode
}>) {
  return (
    <html lang="en">
      <body className={`${inter.className} loading`}>
        <div id="initial-preloader">
          <Image
            src="/logo_wbg.svg"
            alt="App Logo"
            width={120}
            height={120}
            priority
          />
        </div>
        <div id="page-content">
          <ClientLayout>
            <Header />
            {children}
            <BottomNav />
          </ClientLayout>
        </div>
      </body>
    </html>
  )
}
