name: Generate Changelog

on:
  release:
    types: [published]

permissions:
  contents: write

jobs:
  changelog:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
        with:
          fetch-depth: 0

      - name: Install git-cliff
        run: |
          CLIFF_VERSION=2.2.1
          curl -sSL -o git-cliff.tar.gz "https://github.com/orhun/git-cliff/releases/download/v${CLIFF_VERSION}/git-cliff-${CLIFF_VERSION}-x86_64-unknown-linux-gnu.tar.gz"
          tar -xzf git-cliff.tar.gz
          sudo mv git-cliff-${CLIFF_VERSION}/git-cliff /usr/local/bin/

      - name: Generate CHANGELOG.md
        run: git-cliff --config cliff.toml --output CHANGELOG.md

      - name: Commit CHANGELOG
        run: |
          git config user.name "github-actions[bot]"
          git config user.email "github-actions[bot]@users.noreply.github.com"
          git add CHANGELOG.md
          git commit -m "docs(changelog): update release notes"
          git push


